### PR TITLE
Update dependencies for Synthetic PoRep support

### PR DESCRIPTION
**Pull request by cryptonemo**
@Stebalien @ZenGround0  : Looks like there was an update last night that I had trouble rebasing against -- I'm not entirely sure what needs to change to be in sync with it at the moment.

### CODE REVIEW

**Comment by Stebalien** [comment]
A version of ref-fvm was released and updated here. What's the ask?

**Comment by cryptonemo** [comment]
> A version of ref-fvm was released and updated here. What's the ask?

What's the correct version to be using?  I simply tried rebasing against the latest commit and it broke everything :disappointed:

**Comment by Stebalien** [comment]
This patch is broken because there's another patch declaration in the `Cargo.toml` file on master until https://github.com/filecoin-project/builtin-actors/pull/1330 gets merged. Or is something else broken?

**Comment by cryptonemo** [comment]
> 

Yeah, fixing that -- it's still broken here

**Comment by Stebalien** [comment]
Could you push? That's why CI is failing.

**Comment by cryptonemo** [comment]
> Could you push? That's why CI is failing.

Pushed, thanks for looking at.  Seems something is not patched properly, just not sure what it is at this point (fvm).

**Comment by Stebalien** [comment]
Well yes, there's no patch line for the fvm itself.

**Comment by cryptonemo** [comment]
> Well yes, there's no patch line for the fvm itself.

:man_facepalming: Thank you -- sorry, not well versed in the fvm crates and have been staring at patched deps a bit too long.

**Comment by Stebalien** [comment]
Yeah, I know. I do that all the time. The worst is the FFI where we have _two_ FVM versions...

**Comment by jennijuju** [comment]
@cryptonemo can we resolve the conflicts plz?

**Comment by cryptonemo** [comment]
> @cryptonemo can we resolve the conflicts plz?

Looking at, but it'll take me a while to figure out the fvm/filecoin deps that have changed.  I'll likely need assistance if anyone has some cycles (i.e. @Stebalien , @alexytsu )

For starters, is the `alex/update-fvm-ipld` branch of https://github.com/helix-onchain/filecoin still the way to go here?
I'll have to update the fvm branches too and may find related issues.

**Pull request closed without merging**
