### PR TITLE
chore: update fvm/ipld crates

### PR DESCRIPTION
**Pull request by Stebalien**
I'm also moving all the version specifications to the workspace to ensure we always use the same versions and to make future updates easier.

### CODE REVIEW

**Comment by Stebalien** [comment]
See https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table for some context.

**Comment by Stebalien** [comment]
So, this is going to be painful. Basically:

- Our wasm builder version doesn't work with modern rust compiler versions.
- We require modern rust compilers (wasmtime requires them, specifically).
- Newer wasm builder versions compile the "wasm-opt" program and make compile times _very_ **VERY** slow.

We've solved this in ref-fvm by manually building wasm the same way we do in the builtin actors. I have a partial solution to this but..., well, I'll file a PR to demonstrate the issue.

**Comment by alexytsu** [comment]
> I'm also moving all the version specifications to the workspace to ensure we always use the same versions and to make future updates easier.

TIL, thanks.

> We've solved this in ref-fvm by manually building wasm the same way we do in the builtin actors. I have a partial solution to this but..., well, I'll file a PR to demonstrate the issue.

I was following https://github.com/filecoin-project/ref-fvm/pull/1718 and https://github.com/filecoin-project/ref-fvm/pull/1698 to update to stable rust here but didn't quite get all the way yet (on branch `alex/stable-toolchain`)

**Comment by Stebalien** [comment]
Ah! Awesome. This is the branch I currently have: https://github.com/helix-onchain/filecoin/tree/steb/remove-wasm-builder.

**Pull request closed without merging**
